//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBuddhaSite.DataServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfReview
    {
        public System.Guid Id { get; set; }
        public short CompanyRate { get; set; }
        public string CompanyRateRemarks { get; set; }
        public string CompanySuggestions { get; set; }
        public Nullable<System.Guid> CurrentSprintId { get; set; }
        public short SelfInvestmentRate { get; set; }
        public string SelfInvestmentRateRemarks { get; set; }
        public short TasksRate { get; set; }
        public string TasksRateRemarks { get; set; }
        public short TeamRate { get; set; }
        public string TeamRateRemarks { get; set; }
        public string TeamSuggestions { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public short WorkRate { get; set; }
        public string WorkRateRemarks { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
