//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBuddhaSite.DataServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamReview
    {
        public System.Guid Id { get; set; }
        public short AssistsRate { get; set; }
        public Nullable<System.Guid> CurrentSprintId { get; set; }
        public short EffortRate { get; set; }
        public short InnovationRate { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public short MissesRate { get; set; }
        public string Notes { get; set; }
        public short Points { get; set; }
        public short QualityRate { get; set; }
        public string Time { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
