//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBuddhaSite.DataServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.UserTeam = new HashSet<UserTeam>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime CurrentCycle { get; set; }
        public Nullable<System.Guid> CycleId { get; set; }
        public Nullable<System.Guid> DirectorId { get; set; }
        public Nullable<System.Guid> LeadId { get; set; }
        public string Name { get; set; }
        public System.DateTime NextCycle { get; set; }
        public bool UsePreviousReview { get; set; }
        public Nullable<System.Guid> VicePresidentId { get; set; }
        public Nullable<System.Guid> CurrentSprintId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual TeamCycle TeamCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTeam> UserTeam { get; set; }
    }
}
