//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBuddhaSite.DataServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAvatar
    {
        public System.Guid Id { get; set; }
        public System.Guid AvatarId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Avatar Avatar { get; set; }
    }
}
