//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyBuddhaSite.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyBuddhaSite.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error while creating role!.
        /// </summary>
        public static string ErrorRoleCreation {
            get {
                return ResourceManager.GetString("ErrorRoleCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Logged in successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are a NormalUser..
        /// </summary>
        public static string NormalUserMsg {
            get {
                return ResourceManager.GetString("NormalUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Happy Buddha - Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User account locked out..
        /// </summary>
        public static string UserAccountLocked {
            get {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
